apiVersion: v1
kind: Service
metadata:
  name: udp-coturn-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "3478"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP 
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"   
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
  - protocol: UDP
    port: 55000
    targetPort: 55000
    name: exposed-port-55000
  - protocol: UDP
    port: 55001
    targetPort: 55001
    name: exposed-port-55001
  - protocol: UDP
    port: 55002
    targetPort: 55002
    name: exposed-port-55002
  - protocol: UDP
    port: 55003
    targetPort: 55003
    name: exposed-port-55003
  - protocol: UDP
    port: 55004
    targetPort: 55004
    name: exposed-port-55004
  - protocol: UDP
    port: 55005
    targetPort: 55005
    name: exposed-port-55005
  - protocol: UDP
    port: 55006
    targetPort: 55006
    name: exposed-port-55006
  - protocol: UDP
    port: 55007
    targetPort: 55007
    name: exposed-port-55007
  - protocol: UDP
    port: 55008
    targetPort: 55008
    name: exposed-port-55008
  - protocol: UDP
    port: 55009
    targetPort: 55009
    name: exposed-port-55009
  - protocol: UDP
    port: 55010
    targetPort: 55010
    name: exposed-port-55010
  selector:
    app: coturn
  type: LoadBalancer