apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: coturn
  name: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coturn
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: coturn
        app: coturn
    spec:
      containers:
        - env:
            - name: IS_TURN_ON_AWS
              value: "true"
            - name: PRIVATE_IP
            - name: PUBLIC_IP
            - name: TURN_PASSWORD
            - name: TURN_USER
          image: 376474804475.dkr.ecr.eu-west-1.amazonaws.com/recording-turn:latest
          name: coturn
          ports:
            - containerPort: 3478
              protocol: TCP
            - protocol: UDP
              containerPort: 55000
            - protocol: UDP
              containerPort: 55001
            - protocol: UDP
              containerPort: 55002
            - protocol: UDP
              containerPort: 55003
            - protocol: UDP
              containerPort: 55004
            - protocol: UDP
              containerPort: 55005
            - protocol: UDP
              containerPort: 55006
            - protocol: UDP
              containerPort: 55007
            - protocol: UDP
              containerPort: 55008
            - protocol: UDP
              containerPort: 55009
            - protocol: UDP
              containerPort: 55010
            - protocol: UDP
              containerPort: 55011
            - protocol: UDP
              containerPort: 55012
            - protocol: UDP
              containerPort: 55013
            - protocol: UDP
              containerPort: 55014
            - protocol: UDP
              containerPort: 55015
            - protocol: UDP
              containerPort: 55016
            - protocol: UDP
              containerPort: 55017
            - protocol: UDP
              containerPort: 55018
            - protocol: UDP
              containerPort: 55019
            - protocol: UDP
              containerPort: 55020
            - protocol: UDP
              containerPort: 55021
            - protocol: UDP
              containerPort: 55022
            - protocol: UDP
              containerPort: 55023
            - protocol: UDP
              containerPort: 55024
            - protocol: UDP
              containerPort: 55025
            - protocol: UDP
              containerPort: 55026
            - protocol: UDP
              containerPort: 55027
            - protocol: UDP
              containerPort: 55028
            - protocol: UDP
              containerPort: 55029
            - protocol: UDP
              containerPort: 55030
            - protocol: UDP
              containerPort: 55031
            - protocol: UDP
              containerPort: 55032
            - protocol: UDP
              containerPort: 55033
            - protocol: UDP
              containerPort: 55034
            - protocol: UDP
              containerPort: 55035
            - protocol: UDP
              containerPort: 55036
            - protocol: UDP
              containerPort: 55037
            - protocol: UDP
              containerPort: 55038
            - protocol: UDP
              containerPort: 55039
            - protocol: UDP
              containerPort: 55040
            - protocol: UDP
              containerPort: 55041
            - protocol: UDP
              containerPort: 55042
            - protocol: UDP
              containerPort: 55043
            - protocol: UDP
              containerPort: 55044
            - protocol: UDP
              containerPort: 55045
            - protocol: UDP
              containerPort: 55046
            - protocol: UDP
              containerPort: 55047
            - protocol: UDP
              containerPort: 55048
            - protocol: UDP
              containerPort: 55049
            - protocol: UDP
              containerPort: 55050
            - protocol: UDP
              containerPort: 55051
            - protocol: UDP
              containerPort: 55052
            - protocol: UDP
              containerPort: 55053
            - protocol: UDP
              containerPort: 55054
            - protocol: UDP
              containerPort: 55055
            - protocol: UDP
              containerPort: 55056
            - protocol: UDP
              containerPort: 55057
            - protocol: UDP
              containerPort: 55058
            - protocol: UDP
              containerPort: 55059
            - protocol: UDP
              containerPort: 55060
            - protocol: UDP
              containerPort: 55061
            - protocol: UDP
              containerPort: 55062
            - protocol: UDP
              containerPort: 55063
            - protocol: UDP
              containerPort: 55064
            - protocol: UDP
              containerPort: 55065
            - protocol: UDP
              containerPort: 55066
            - protocol: UDP
              containerPort: 55067
            - protocol: UDP
              containerPort: 55068
            - protocol: UDP
              containerPort: 55069
            - protocol: UDP
              containerPort: 55070
            - protocol: UDP
              containerPort: 55071
            - protocol: UDP
              containerPort: 55072
            - protocol: UDP
              containerPort: 55073
            - protocol: UDP
              containerPort: 55074
            - protocol: UDP
              containerPort: 55075
            - protocol: UDP
              containerPort: 55076
            - protocol: UDP
              containerPort: 55077
            - protocol: UDP
              containerPort: 55078
            - protocol: UDP
              containerPort: 55079
            - protocol: UDP
              containerPort: 55080
            - protocol: UDP
              containerPort: 55081
            - protocol: UDP
              containerPort: 55082
            - protocol: UDP
              containerPort: 55083
            - protocol: UDP
              containerPort: 55084
            - protocol: UDP
              containerPort: 55085
            - protocol: UDP
              containerPort: 55086
            - protocol: UDP
              containerPort: 55087
            - protocol: UDP
              containerPort: 55088
            - protocol: UDP
              containerPort: 55089
            - protocol: UDP
              containerPort: 55090
            - protocol: UDP
              containerPort: 55091
            - protocol: UDP
              containerPort: 55092
            - protocol: UDP
              containerPort: 55093
            - protocol: UDP
              containerPort: 55094
            - protocol: UDP
              containerPort: 55095
            - protocol: UDP
              containerPort: 55096
            - protocol: UDP
              containerPort: 55097
            - protocol: UDP
              containerPort: 55098
            - protocol: UDP
              containerPort: 55099
            - protocol: UDP
              containerPort: 55100
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/log/turnserver/
              name: coturn-claim0
      restartPolicy: Always
      volumes:
        - name: coturn-claim0
          persistentVolumeClaim:
            claimName: coturn-claim0
status: {}
