apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: kurento-worker
  name: kurento-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kurento-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: kurento-worker
        app: kurento-worker
    spec:
      containers:
        - env:
            - name: TURN_URL
              value: ':@:'
          image: 376474804475.dkr.ecr.eu-west-1.amazonaws.com/recording-kurento:latest
          name: kurento-worker
          ports:
            - containerPort: 8888
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/log/kurento-media-server/
              name: kurento-worker-claim0
            - mountPath: /rec
              name: kurento-worker-claim1
            - name: persistent-storage
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: kurento-worker-claim0
          persistentVolumeClaim:
            claimName: kurento-worker-claim0
        - name: kurento-worker-claim1
          persistentVolumeClaim:
            claimName: kurento-worker-claim1
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-storage-claim
status: {}
