apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: play
  name: play
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: play
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: play
        app: play
    spec:
      containers:
        - env:
            - name: PLAYBACK_BASE_URL
              value: "https://videome.leadsecure.com"
            - name: PLAYSVC_LISTEN_PORT
              value: "9001"
          image: 376474804475.dkr.ecr.eu-west-1.amazonaws.com/recording-play:latest
          name: play-worker
          ports:
            - containerPort: 9001
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /playsvc/log/
              name: play-claim0
            - mountPath: /rec
              name: play-claim1
            - name: persistent-storage
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: play-claim0
          persistentVolumeClaim:
            claimName: play-claim0
        - name: play-claim1
          persistentVolumeClaim:
            claimName: play-claim1
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-storage-claim
status: {}
