apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: play-claim0
  name: play-claim0
spec:
  storageClassName: gp2
  volumeName: local-pv3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv3
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gp2"
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    namespace: default
    name: play-claim0
