apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: processing-worker
  name: processing-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processing-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: processing-worker
        app: processing-worker
    spec:
      containers:
        - env:
            - name: PLAYBACK_BASE_URL
              value: https://videome.leadsecure.com
          image: 376474804475.dkr.ecr.eu-west-1.amazonaws.com/recording-processing:latest
          name: processing-worker
          ports:
            - containerPort: 7002
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /recsvc/log/
              name: processing-worker-claim0
            - mountPath: /var/log/supervisor/
              name: processing-worker-claim1
            - mountPath: /rec
              name: processing-worker-claim2
            - name: persistent-storage
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: processing-worker-claim0
          persistentVolumeClaim:
            claimName: processing-worker-claim0
        - name: processing-worker-claim1
          persistentVolumeClaim:
            claimName: processing-worker-claim1
        - name: processing-worker-claim2
          persistentVolumeClaim:
            claimName: processing-worker-claim2
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-storage-claim
status: {}
