apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: processing-worker-claim2
  name: processing-worker-claim2
spec:
  storageClassName: gp2
  volumeName: local-pv8
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv8
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gp2"
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    namespace: default
    name: processing-worker-claim2
